FROM resin/%%RESIN_MACHINE_NAME%%-python
#For pushing to resin.io
RUN apt-get update && apt-get install -yq python3-pip && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN pip3 install gpiozero RPi.GPIO thingspeak requests

COPY . ./

ENV INITSYSTEM on

CMD ["bash","src/main.bash"]
